name: Rust Test

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Testing
      run: |
        cd ./../002-devops-dojo-cicd-with-github-action/api/ && cargo test --verbose
